export const defaultLocale = "en";
export const supportedLocales = Object.freeze(["en", "vi"]);

export const languageOptions = Object.freeze([
  { label: "Auto", value: "system" },
  { label: "English", value: "en" },
  { label: "Tiếng Việt", value: "vi" },
]);

const messages = {
  en: {
    "tabs.overview": "Overview",
    "tabs.benchmark": "Benchmark",
    "tabs.catalog": "Catalog",
    "tabs.storage": "Storage",
    "tabs.policy": "Policy",
    "nav.notFound": "Not Found",

    "common.add": "Add",
    "common.update": "Update",
    "common.delete": "Delete",
    "common.refresh": "Refresh",
    "common.search": "Search",
    "common.custom": "custom",
    "common.none": "none",
    "common.unknown": "unknown",
    "common.yes": "yes",
    "common.no": "no",
    "common.up": "up",
    "common.down": "down",
    "common.system": "system",
    "common.direct": "direct",
    "common.default": "Default",
    "common.vietnam": "Vietnam",
    "common.enabled": "on",
    "common.disabled": "off",
    "common.continue": "Continue",
    "status.idle": "idle",
    "status.running": "running",
    "status.success": "success",
    "status.failed": "failed",

    "language.title": "Language",
    "language.subtitle": "Auto follows the OS language. Vietnamese and English can be selected manually for real-device checks.",
    "language.auto": "Auto",

    "overview.title": "DNSPilot Mobile",
    "overview.subtitle": "Expo mobile app for testing DNSPilot core and CLI contracts through a local bridge. It never silently changes system DNS.",
    "overview.bridgeUrl": "Bridge URL",
    "overview.useUrl": "Use URL",
    "overview.initDb": "Init DB",
    "device.title": "Device Setup",
    "device.subtitle": "Pick the test target before pasting a bridge URL. Physical devices need the Mac LAN URL printed by npm run bridge.",
    "device.target.ios-device": "iOS device",
    "device.target.android-device": "Android device",
    "device.target.ios-simulator": "iOS Simulator",
    "device.target.android-emulator": "Android emulator",
    "device.target.web": "Web",
    "device.metric.bridge": "Bridge URL",
    "device.metric.permission": "Permission",
    "device.metric.policy": "DNS mutation",
    "device.policy.noMutation": "Store-safe consumer mode: guided settings only, no silent system DNS mutation, no Android VpnService, and no speed-improvement claim.",
    "device.useNormalized": "Normalize URL",
    "device.useAndroidEmulator": "Use emulator URL",
    "device.code.bridge-url-missing": "Enter a bridge URL.",
    "device.code.localhost-not-device-reachable": "localhost is not reachable from a physical phone. Use the Mac LAN URL.",
    "device.code.android-emulator-needs-10-0-2-2": "Android emulator should use http://10.0.2.2:8787.",
    "device.code.device-needs-private-lan": "Physical devices should use a private LAN URL from npm run bridge.",
    "device.code.bridge-ready": "Bridge is reachable.",
    "device.code.bridge-not-verified": "Bridge URL looks usable; tap Refresh to verify.",
    "device.code.ios-local-network": "iOS/iPadOS may ask for Local Network permission.",
    "device.code.android-normal-network": "Android uses normal network access; no dangerous runtime prompt expected.",
    "device.code.web-browser-network": "Browser network access only.",
    "settings.noneAvailable": "none available",
    "settings.protected.title.ios": "iOS/iPadOS Protected network detected",
    "settings.protected.title.android": "Android Protected network detected",
    "settings.protected.step": "Keep current DNS settings. Do not offer apply prompts until protected-network signals clear.",
    "settings.protected.claim": "Protect current DNS on VPN, MDM, corporate DNS, or captive portal networks.",
    "settings.android.title": "Android guided DNS settings",
    "settings.android.review": "Review {profileName} after the foreground benchmark result.",
    "settings.android.open": "Use Android Settings > Network & internet > Private DNS or network DNS settings where the device supports it.",
    "settings.android.copy": "Copy DNS servers for manual entry: {servers}.",
    "settings.android.retest": "Retest with System DNS validation after the user changes settings.",
    "settings.android.claim": "Guided settings only. No VpnService and no hidden DNS changes in the consumer app.",
    "settings.ios.title": "iOS/iPadOS DNS Settings guidance",
    "settings.ios.review": "Review {profileName} after the foreground benchmark result.",
    "settings.ios.profile": "Use a user-approved DNS Settings profile when NetworkExtension entitlement and review allow it.",
    "settings.ios.copy": "Copy DNS servers for manual/profile entry: {servers}.",
    "settings.ios.retest": "Retest with System DNS validation after the user enables the profile or changes settings.",
    "settings.ios.claim": "Guidance only for plain DNS. No DNSJumper-style system DNS switching.",
    "settings.action.copyDns": "Copy DNS servers",
    "settings.action.openSettings": "Open Settings",
    "settings.action.applyAndroid": "Apply in OS DNS settings",
    "settings.action.prepareIos": "Prepare DNS profile/settings",
    "settings.action.retestSystemDns": "Retest System DNS",
    "settings.action.copied": "DNS servers copied.",
    "settings.action.openedSettings": "Settings opened.",
    "settings.action.prepared": "Copied DNS values and opened Settings.",
    "settings.action.retesting": "Retesting System DNS...",
    "settings.action.retested": "System DNS retest complete.",
    "systemAccess.title": "System Access",
    "systemAccess.summary.ios": "DNSPilot checks Local Network access for bridge testing. iOS DNS apply and DNS cache flush are OS-controlled; the app will open settings and retest instead of silently changing DNS.",
    "systemAccess.summary.android": "DNSPilot checks network access and opens Android DNS settings when you choose to apply. The app does not use VpnService, hidden Private DNS mutation, or speed-improvement claims.",
    "systemAccess.check.localNetwork": "Local Network",
    "systemAccess.check.networkAccess": "Network access",
    "systemAccess.check.privateDns": "Private DNS settings",
    "systemAccess.check.dnsApply": "Apply DNS",
    "systemAccess.check.dnsFlush": "Flush DNS",
    "systemAccess.detail.localNetwork": "Allow Local Network if iOS prompts while connecting to the bridge. Use App Settings if it was denied.",
    "systemAccess.detail.networkAccess": "Android uses normal INTERNET and network-state permissions; no dangerous runtime prompt is expected.",
    "systemAccess.detail.privateDns": "Private DNS and Wi-Fi DNS are changed by the user in Android Settings, not silently by the app.",
    "systemAccess.detail.dnsApply": "Mobile OS policy requires user-approved settings/profile flow for consumer builds.",
    "systemAccess.detail.dnsFlush": "iOS and Android do not expose a store-safe third-party system DNS cache flush API. Retest System DNS after changes.",
    "systemAccess.action.openAppSettings": "Open App Settings",
    "systemAccess.action.openNetworkSettings": "Open Network Settings",
    "systemAccess.action.openPrivateDns": "Open Private DNS",
    "systemAccess.action.retestSystemDns": "Retest System DNS",
    "systemAccess.settings.opened": "Settings opened.",
    "systemAccess.settings.failed": "Could not open Settings on this OS build.",
    "systemAccess.retest.running": "Retesting System DNS...",
    "systemAccess.retest.done": "System DNS retest complete.",
    "systemAccess.retest.failed": "System DNS retest failed. Check the bridge and OS settings.",
    "systemAccess.status.ready": "ready",
    "systemAccess.status.unknown": "unknown",
    "systemAccess.status.needs-action": "needs action",
    "systemAccess.status.os-gated": "OS gated",
    "systemAccess.status.unsupported": "unsupported",
    "overview.status.title": "Status",
    "overview.status.subtitleReady": "SQLite: {path}",
    "overview.status.subtitleMissing": "Start npm run bridge before testing.",
    "overview.metric.bridge": "Bridge",
    "overview.metric.profiles": "Profiles",
    "overview.metric.suites": "Suites",
    "overview.metric.capabilities": "Capabilities",
    "overview.metric.history": "History",
    "overview.smoke.title": "Smoke Sample",
    "overview.smoke.subtitle": "Uses dnspilot-cli recommend-sample, not mobile-side scoring.",
    "overview.smoke.run": "Run sample recommendation",
    "overview.boundary.title": "Native Boundary",
    "overview.boundary.subtitle": "Store-safe mobile behavior is capability-based. DNS settings are guided, not silently mutated.",
    "overview.boundary.coveredTitle": "Covered CLI surface",
    "overview.boundary.coveredBody": "Catalog, capabilities, preflight, apply policy, apply plan, benchmark, system benchmark, compare, path estimate, path compare, profile storage, suite storage, history, and sample recommendation.",
    "overview.native.title": "Native Permissions",
    "overview.native.subtitle": "Standalone builds include native network metadata for real-device bridge testing and store review copy.",
    "overview.native.ios": "iOS/iPadOS asks for Local Network only when connecting to a local bridge or LAN diagnostic endpoint. DNS Settings profile capability still requires Apple entitlement/review.",
    "overview.native.android": "Android uses normal network access for benchmark/bridge calls. The consumer build does not request VpnService and does not mutate Private DNS silently.",

    "benchmark.run.title": "Run",
    "benchmark.run.subtitle": "Foreground only. Long worst-case plans keep the app on this screen until CLI returns.",
    "benchmark.mode.compare": "DNS Compare",
    "benchmark.mode.pathCompare": "DNS + TCP",
    "benchmark.mode.benchmark": "Single DNS",
    "benchmark.mode.pathEstimate": "Single path",
    "benchmark.mode.systemBenchmark": "System DNS",
    "benchmark.family.both": "A + AAAA",
    "benchmark.family.ipv4Only": "A only",
    "benchmark.family.ipv6Only": "AAAA only",
    "platform.ios": "iOS",
    "platform.android": "Android",
    "benchmark.help.family": "A + AAAA tests IPv4 and IPv6 answers. Use A only when IPv6 looks broken on the current network. Use AAAA only to isolate IPv6 resolver behavior.",
    "benchmark.metric.selected": "Selected",
    "benchmark.metric.domains": "Domains",
    "benchmark.metric.platform": "Platform",
    "benchmark.metric.history": "History",
    "benchmark.domains": "Domains",
    "benchmark.attempts": "Attempts",
    "benchmark.dnsTimeout": "DNS timeout ms",
    "benchmark.tcpTimeout": "TCP timeout ms",
    "benchmark.maxTargets": "Max targets/domain",
    "benchmark.tlsTiming": "TLS/SNI timing",
    "benchmark.tlsTimingHelp": "Adds TLS handshake samples where supported.",
    "benchmark.saveHistory": "Save history",
    "benchmark.saveHistoryHelp": "Available for compare/path-compare/benchmark.",
    "benchmark.runButton": "Run benchmark",
    "benchmark.profiles.title": "Profiles",
    "benchmark.profiles.subtitle": "Plain DNS profiles only. Custom profiles saved in Storage appear here.",
    "benchmark.profiles.empty": "Refresh Overview or start the bridge to load profiles.",
    "benchmark.process.title": "Process",
    "benchmark.process.subtitleReady": "{status} | {reason}",
    "benchmark.process.subtitleEmpty": "Run a benchmark to populate process diagnostics.",
    "benchmark.metric.status": "Status",
    "benchmark.metric.failedStep": "Failed step",
    "benchmark.metric.elapsed": "Elapsed",
    "benchmark.failedStepNone": "none",
    "benchmark.copyReport": "Copy report",
    "benchmark.reportCopied": "Report copied.",
    "benchmark.noDiagnostics": "No process diagnostics yet.",
    "benchmark.suites.title": "Suites",
    "benchmark.suites.subtitle": "Optional. Domains above are added to suite domains.",
    "benchmark.noSuite": "No suite",
    "benchmark.suiteAdds": "Selected suite adds {count} domains: {domains}",
    "benchmark.result.title": "Result",
    "benchmark.result.subtitleReady": "CLI: {args}",
    "benchmark.result.subtitleEmpty": "Run a benchmark to see parsed JSON.",
    "benchmark.metric.progressEvents": "Progress events",
    "benchmark.metric.action": "Action",
    "benchmark.recommendation": "Recommendation",
    "benchmark.noResult": "No benchmark result yet.",
    "benchmark.guided.title": "Guided DNS Settings",
    "benchmark.guided.subtitle": "Store-safe next step from the benchmark recommendation. No silent system DNS mutation.",
    "benchmark.toggle.vpn": "VPN active",
    "benchmark.toggle.mdm": "MDM active",
    "benchmark.toggle.corporateDns": "Corporate DNS",
    "benchmark.toggle.captivePortal": "Captive portal",
    "benchmark.metric.recommended": "Recommended",
    "benchmark.metric.health": "Health",
    "benchmark.metric.confidence": "Confidence",
    "benchmark.loadGuidedPlan": "Load guided settings plan",
    "benchmark.noGuidedPlan": "No guided settings plan is available because the benchmark did not return a recommendation.",

    "catalog.title": "Catalog",
    "catalog.subtitle": "Core-owned provider and suite contracts. Custom storage entries are merged by the CLI.",
    "catalog.placeholder": "cloudflare, family, vietnam",
    "catalog.filter.all": "All",
    "catalog.filter.plain": "Plain",
    "catalog.filter.encrypted": "DoH/DoT",
    "catalog.filter.custom": "Custom",
    "catalog.metric.mobilePlatforms": "Mobile platforms",
    "catalog.refresh": "Refresh catalog",
    "catalog.profiles.title": "Profiles",
    "catalog.profiles.subtitle": "{count} matching profiles",
    "catalog.profiles.empty": "No profiles match the current filter.",
    "catalog.profile.meta": "ID: {id} | Filtering: {filtering} | Servers: {servers}",
    "catalog.suites.title": "Test Suites",
    "catalog.suites.subtitle": "Built-in and custom domain groups used by benchmark commands.",
    "catalog.suites.empty": "No suites loaded.",

    "policy.title": "Policy",
    "policy.subtitle": "Mobile store-safe apply guidance. Protected-network signals should suppress risky apply prompts.",
    "policy.metric.apply": "Apply",
    "policy.metric.flush": "Flush",
    "policy.metric.storeSafe": "Store safe",
    "policy.input.title": "Recommendation Input",
    "policy.input.subtitle": "Simulates the completed benchmark result passed into apply-plan.",
    "policy.testedResolver": "Tested resolver",
    "policy.protected.title": "Protected Network Signals",
    "policy.protected.subtitle": "These flags should force protect-current-dns or remove apply prompts when needed.",
    "policy.loadPayloads": "Load policy payloads",
    "policy.guided.title": "Guided Flow",
    "policy.guided.subtitle": "Capability-based OS flow. The app does not silently mutate system DNS.",
    "policy.metric.mutatesDns": "Mutates DNS",
    "policy.metric.steps": "Steps",
    "policy.guided.empty": "Load policy payloads to generate the OS guidance flow.",
    "policy.payloads.title": "Payloads",
    "policy.payloads.subtitle": "Raw core/CLI JSON is selectable for issue reports.",
    "policy.payloads.empty": "No policy payload loaded yet.",
    "policy.option.healthy": "Healthy",
    "policy.option.degraded": "Degraded",
    "policy.option.failed": "Failed",
    "policy.option.inconclusive": "Inconclusive",
    "policy.option.high": "High",
    "policy.option.medium": "Medium",
    "policy.option.low": "Low",

    "storage.title": "Storage",
    "storage.subtitle": "SQLite-backed custom DNS profiles, domain suites, and benchmark history.",
    "storage.metric.customProfiles": "Custom profiles",
    "storage.metric.customSuites": "Custom suites",
    "storage.refresh": "Refresh storage",
    "storage.profile.title": "Custom DNS Profile",
    "storage.profile.subtitle": "Plain profiles can be benchmarked. DoH/DoT profiles are saved for catalog/apply guidance.",
    "storage.profile.id": "ID",
    "storage.profile.name": "Name",
    "storage.protocol.plain": "Plain",
    "storage.protocol.doh": "DoH",
    "storage.protocol.dot": "DoT",
    "storage.filtering.none": "None",
    "storage.filtering.malware": "Malware",
    "storage.filtering.family": "Family",
    "storage.filtering.ads": "Ads",
    "storage.filtering.security": "Security",
    "storage.profile.ipv4": "IPv4 servers",
    "storage.profile.ipv6": "IPv6 servers",
    "storage.profile.doh": "DoH URL",
    "storage.profile.dot": "DoT hostname",
    "storage.profile.tags": "Tags",
    "storage.profile.update": "Update",
    "storage.suite.title": "Custom Domain Suite",
    "storage.suite.subtitle": "Suites plug into benchmark, compare, path-estimate, and path-compare.",
    "storage.suite.id": "ID",
    "storage.suite.name": "Name",
    "storage.suite.domains": "Domains",
    "storage.suite.tags": "Tags",
    "storage.suite.add": "Add suite",
    "storage.suite.update": "Update suite",
    "storage.suite.delete": "Delete suite",
    "storage.history.title": "History",
    "storage.history.subtitle": "Saved by benchmark commands with Save history enabled.",
    "storage.history.clear": "Clear history",
    "storage.history.empty": "No saved benchmark history.",
    "storage.history.record": "{scope} | {mode} | recommended {recommendation}",
    "storage.history.delete": "Delete record",
    "storage.lastResult.title": "Last CLI Result",
    "storage.lastResult.empty": "No storage action result yet.",

    "test.fallbackCount": "{count} profiles",
  },
  vi: {
    "tabs.overview": "Tổng quan",
    "tabs.benchmark": "Benchmark",
    "tabs.catalog": "Catalog",
    "tabs.storage": "Lưu trữ",
    "tabs.policy": "Policy",
    "nav.notFound": "Không tìm thấy",

    "common.add": "Thêm",
    "common.update": "Cập nhật",
    "common.delete": "Xóa",
    "common.refresh": "Làm mới",
    "common.search": "Tìm kiếm",
    "common.custom": "tùy chỉnh",
    "common.none": "không có",
    "common.unknown": "chưa rõ",
    "common.yes": "có",
    "common.no": "không",
    "common.up": "đang chạy",
    "common.down": "đang tắt",
    "common.system": "hệ thống",
    "common.direct": "trực tiếp",
    "common.default": "Mặc định",
    "common.vietnam": "Việt Nam",
    "common.enabled": "bật",
    "common.disabled": "tắt",
    "common.continue": "Tiếp tục",
    "status.idle": "chờ",
    "status.running": "đang kiểm tra",
    "status.success": "OK",
    "status.failed": "lỗi",

    "language.title": "Ngôn ngữ",
    "language.subtitle": "Tự động dùng ngôn ngữ hệ điều hành. Có thể chọn Tiếng Việt hoặc English khi test trên thiết bị thật.",
    "language.auto": "Tự động",

    "overview.title": "DNSPilot Mobile",
    "overview.subtitle": "Ứng dụng mobile Expo để test hợp đồng DNSPilot core và CLI qua local bridge. Ứng dụng không âm thầm đổi DNS hệ thống.",
    "overview.bridgeUrl": "Bridge URL",
    "overview.useUrl": "Dùng URL",
    "overview.initDb": "Khởi tạo DB",
    "device.title": "Thiết lập thiết bị",
    "device.subtitle": "Chọn target test trước khi dán Bridge URL. Thiết bị thật cần Mac LAN URL được in bởi npm run bridge.",
    "device.target.ios-device": "iOS device",
    "device.target.android-device": "Android device",
    "device.target.ios-simulator": "iOS Simulator",
    "device.target.android-emulator": "Android emulator",
    "device.target.web": "Web",
    "device.metric.bridge": "Bridge URL",
    "device.metric.permission": "Quyền",
    "device.metric.policy": "Mutate DNS",
    "device.policy.noMutation": "Consumer mode store-safe: chỉ hướng dẫn settings, không âm thầm đổi DNS hệ thống, không dùng Android VpnService, và không claim tăng tốc internet.",
    "device.useNormalized": "Chuẩn hóa URL",
    "device.useAndroidEmulator": "Dùng emulator URL",
    "device.code.bridge-url-missing": "Nhập Bridge URL.",
    "device.code.localhost-not-device-reachable": "localhost không truy cập được từ điện thoại thật. Dùng Mac LAN URL.",
    "device.code.android-emulator-needs-10-0-2-2": "Android emulator nên dùng http://10.0.2.2:8787.",
    "device.code.device-needs-private-lan": "Thiết bị thật nên dùng private LAN URL từ npm run bridge.",
    "device.code.bridge-ready": "Bridge truy cập được.",
    "device.code.bridge-not-verified": "Bridge URL có vẻ dùng được; bấm Làm mới để verify.",
    "device.code.ios-local-network": "iOS/iPadOS có thể hỏi quyền Local Network.",
    "device.code.android-normal-network": "Android dùng network access bình thường; không kỳ vọng dangerous runtime prompt.",
    "device.code.web-browser-network": "Chỉ dùng network access của browser.",
    "settings.noneAvailable": "không có",
    "settings.protected.title.ios": "iOS/iPadOS phát hiện protected network",
    "settings.protected.title.android": "Android phát hiện protected network",
    "settings.protected.step": "Giữ DNS hiện tại. Không hiển thị prompt apply cho đến khi tín hiệu protected-network hết.",
    "settings.protected.claim": "Bảo vệ DNS hiện tại trên mạng VPN, MDM, corporate DNS, hoặc captive portal.",
    "settings.android.title": "Hướng dẫn DNS settings Android",
    "settings.android.review": "Xem lại {profileName} sau benchmark foreground.",
    "settings.android.open": "Mở Android Settings > Network & internet > Private DNS hoặc network DNS settings nếu thiết bị hỗ trợ.",
    "settings.android.copy": "Copy DNS server để nhập thủ công: {servers}.",
    "settings.android.retest": "Retest bằng System DNS validation sau khi người dùng đổi settings.",
    "settings.android.claim": "Chỉ hướng dẫn settings. Không dùng VpnService và không đổi DNS ẩn trong consumer app.",
    "settings.ios.title": "Hướng dẫn DNS Settings iOS/iPadOS",
    "settings.ios.review": "Xem lại {profileName} sau benchmark foreground.",
    "settings.ios.profile": "Dùng profile DNS Settings do người dùng duyệt khi NetworkExtension entitlement và review cho phép.",
    "settings.ios.copy": "Copy DNS server để nhập thủ công/profile: {servers}.",
    "settings.ios.retest": "Retest bằng System DNS validation sau khi người dùng bật profile hoặc đổi settings.",
    "settings.ios.claim": "Chỉ hướng dẫn cho plain DNS. Không có kiểu đổi DNS hệ thống như DNSJumper.",
    "settings.action.copyDns": "Copy DNS server",
    "settings.action.openSettings": "Mở Settings",
    "settings.action.applyAndroid": "Apply trong OS DNS settings",
    "settings.action.prepareIos": "Chuẩn bị DNS profile/settings",
    "settings.action.retestSystemDns": "Retest System DNS",
    "settings.action.copied": "Đã copy DNS server.",
    "settings.action.openedSettings": "Đã mở Settings.",
    "settings.action.prepared": "Đã copy DNS và mở Settings.",
    "settings.action.retesting": "Đang retest System DNS...",
    "settings.action.retested": "Retest System DNS xong.",
    "systemAccess.title": "Quyền hệ thống",
    "systemAccess.summary.ios": "DNSPilot kiểm tra Local Network để test bridge. Apply DNS và flush DNS cache trên iOS do OS kiểm soát; app sẽ mở settings và retest thay vì âm thầm đổi DNS.",
    "systemAccess.summary.android": "DNSPilot kiểm tra network access và mở Android DNS settings khi bạn chọn apply. App không dùng VpnService, không âm thầm đổi Private DNS, và không claim tăng tốc.",
    "systemAccess.check.localNetwork": "Local Network",
    "systemAccess.check.networkAccess": "Network access",
    "systemAccess.check.privateDns": "Private DNS settings",
    "systemAccess.check.dnsApply": "Apply DNS",
    "systemAccess.check.dnsFlush": "Flush DNS",
    "systemAccess.detail.localNetwork": "Cho phép Local Network nếu iOS hỏi khi kết nối bridge. Dùng App Settings nếu đã deny.",
    "systemAccess.detail.networkAccess": "Android dùng quyền INTERNET và network-state bình thường; không kỳ vọng dangerous runtime prompt.",
    "systemAccess.detail.privateDns": "Private DNS và Wi-Fi DNS do người dùng đổi trong Android Settings, không bị app đổi ẩn.",
    "systemAccess.detail.dnsApply": "Policy mobile OS yêu cầu flow settings/profile do người dùng duyệt cho consumer build.",
    "systemAccess.detail.dnsFlush": "iOS và Android không có API store-safe cho app bên thứ ba flush system DNS cache. Retest System DNS sau khi đổi.",
    "systemAccess.action.openAppSettings": "Mở App Settings",
    "systemAccess.action.openNetworkSettings": "Mở Network Settings",
    "systemAccess.action.openPrivateDns": "Mở Private DNS",
    "systemAccess.action.retestSystemDns": "Retest System DNS",
    "systemAccess.settings.opened": "Đã mở Settings.",
    "systemAccess.settings.failed": "Không mở được Settings trên bản OS này.",
    "systemAccess.retest.running": "Đang retest System DNS...",
    "systemAccess.retest.done": "Retest System DNS hoàn tất.",
    "systemAccess.retest.failed": "Retest System DNS thất bại. Kiểm tra bridge và OS settings.",
    "systemAccess.status.ready": "sẵn sàng",
    "systemAccess.status.unknown": "chưa rõ",
    "systemAccess.status.needs-action": "cần thao tác",
    "systemAccess.status.os-gated": "OS kiểm soát",
    "systemAccess.status.unsupported": "không hỗ trợ",
    "overview.status.title": "Trạng thái",
    "overview.status.subtitleReady": "SQLite: {path}",
    "overview.status.subtitleMissing": "Chạy npm run bridge trước khi test.",
    "overview.metric.bridge": "Bridge",
    "overview.metric.profiles": "Profile",
    "overview.metric.suites": "Suite",
    "overview.metric.capabilities": "Capability",
    "overview.metric.history": "Lịch sử",
    "overview.smoke.title": "Smoke sample",
    "overview.smoke.subtitle": "Dùng dnspilot-cli recommend-sample, không chấm điểm ở mobile.",
    "overview.smoke.run": "Chạy sample recommendation",
    "overview.boundary.title": "Ranh giới native",
    "overview.boundary.subtitle": "Hành vi mobile store-safe dựa trên capability. DNS settings là flow hướng dẫn, không âm thầm mutate.",
    "overview.boundary.coveredTitle": "CLI surface đã cover",
    "overview.boundary.coveredBody": "Catalog, capabilities, preflight, apply policy, apply plan, benchmark, system benchmark, compare, path estimate, path compare, profile storage, suite storage, history, và sample recommendation.",
    "overview.native.title": "Quyền native",
    "overview.native.subtitle": "Standalone build có metadata network native cho real-device bridge test và nội dung review store.",
    "overview.native.ios": "iOS/iPadOS chỉ hỏi Local Network khi kết nối local bridge hoặc LAN diagnostic endpoint. DNS Settings profile vẫn cần Apple entitlement/review.",
    "overview.native.android": "Android dùng quyền network bình thường cho benchmark/bridge. Consumer build không xin VpnService và không âm thầm đổi Private DNS.",

    "benchmark.run.title": "Chạy benchmark",
    "benchmark.run.subtitle": "Chỉ chạy foreground. Plan dài sẽ giữ app ở màn hình này đến khi CLI trả kết quả.",
    "benchmark.mode.compare": "So sánh DNS",
    "benchmark.mode.pathCompare": "DNS + TCP",
    "benchmark.mode.benchmark": "DNS đơn",
    "benchmark.mode.pathEstimate": "Đường dẫn đơn",
    "benchmark.mode.systemBenchmark": "DNS hệ thống",
    "benchmark.family.both": "A + AAAA",
    "benchmark.family.ipv4Only": "Chỉ A",
    "benchmark.family.ipv6Only": "Chỉ AAAA",
    "platform.ios": "iOS",
    "platform.android": "Android",
    "benchmark.help.family": "A + AAAA test cả IPv4 và IPv6. Dùng A only khi IPv6 mạng hiện tại có vẻ lỗi. Dùng AAAA only để cô lập hành vi resolver IPv6.",
    "benchmark.metric.selected": "Đã chọn",
    "benchmark.metric.domains": "Domain",
    "benchmark.metric.platform": "Nền tảng",
    "benchmark.metric.history": "Lịch sử",
    "benchmark.domains": "Domain",
    "benchmark.attempts": "Số lần thử",
    "benchmark.dnsTimeout": "DNS timeout ms",
    "benchmark.tcpTimeout": "TCP timeout ms",
    "benchmark.maxTargets": "Max target/domain",
    "benchmark.tlsTiming": "TLS/SNI timing",
    "benchmark.tlsTimingHelp": "Thêm mẫu TLS handshake khi được hỗ trợ.",
    "benchmark.saveHistory": "Lưu lịch sử",
    "benchmark.saveHistoryHelp": "Áp dụng cho compare/path-compare/benchmark.",
    "benchmark.runButton": "Chạy benchmark",
    "benchmark.profiles.title": "Profile",
    "benchmark.profiles.subtitle": "Chỉ plain DNS profile. Custom profile lưu ở Storage sẽ hiện tại đây.",
    "benchmark.profiles.empty": "Làm mới Overview hoặc chạy bridge để tải profile.",
    "benchmark.process.title": "Tiến trình",
    "benchmark.process.subtitleReady": "{status} | {reason}",
    "benchmark.process.subtitleEmpty": "Chạy benchmark để có diagnostics tiến trình.",
    "benchmark.metric.status": "Trạng thái",
    "benchmark.metric.failedStep": "Step lỗi",
    "benchmark.metric.elapsed": "Thời gian",
    "benchmark.failedStepNone": "không có",
    "benchmark.copyReport": "Copy report",
    "benchmark.reportCopied": "Đã copy report.",
    "benchmark.noDiagnostics": "Chưa có diagnostics tiến trình.",
    "benchmark.suites.title": "Suite",
    "benchmark.suites.subtitle": "Tùy chọn. Domain bên trên được cộng thêm vào domain của suite.",
    "benchmark.noSuite": "Không dùng suite",
    "benchmark.suiteAdds": "Suite đã chọn thêm {count} domain: {domains}",
    "benchmark.result.title": "Kết quả",
    "benchmark.result.subtitleReady": "CLI: {args}",
    "benchmark.result.subtitleEmpty": "Chạy benchmark để xem JSON đã parse.",
    "benchmark.metric.progressEvents": "Progress event",
    "benchmark.metric.action": "Action",
    "benchmark.recommendation": "Recommendation",
    "benchmark.noResult": "Chưa có kết quả benchmark.",
    "benchmark.guided.title": "Hướng dẫn DNS Settings",
    "benchmark.guided.subtitle": "Bước tiếp theo store-safe từ recommendation. Không âm thầm mutate DNS hệ thống.",
    "benchmark.toggle.vpn": "VPN đang bật",
    "benchmark.toggle.mdm": "MDM đang bật",
    "benchmark.toggle.corporateDns": "Corporate DNS",
    "benchmark.toggle.captivePortal": "Captive portal",
    "benchmark.metric.recommended": "Đề xuất",
    "benchmark.metric.health": "Health",
    "benchmark.metric.confidence": "Độ tin cậy",
    "benchmark.loadGuidedPlan": "Tải guided settings plan",
    "benchmark.noGuidedPlan": "Không có guided settings plan vì benchmark chưa trả recommendation.",

    "catalog.title": "Catalog",
    "catalog.subtitle": "Provider và suite contract do core sở hữu. Entry custom từ storage được CLI merge.",
    "catalog.placeholder": "cloudflare, family, vietnam",
    "catalog.filter.all": "Tất cả",
    "catalog.filter.plain": "Plain",
    "catalog.filter.encrypted": "DoH/DoT",
    "catalog.filter.custom": "Custom",
    "catalog.metric.mobilePlatforms": "Mobile platform",
    "catalog.refresh": "Làm mới catalog",
    "catalog.profiles.title": "Profile",
    "catalog.profiles.subtitle": "{count} profile khớp",
    "catalog.profiles.empty": "Không có profile nào khớp filter hiện tại.",
    "catalog.profile.meta": "ID: {id} | Filtering: {filtering} | Server: {servers}",
    "catalog.suites.title": "Test suite",
    "catalog.suites.subtitle": "Nhóm domain built-in và custom dùng cho benchmark command.",
    "catalog.suites.empty": "Chưa tải suite.",

    "policy.title": "Policy",
    "policy.subtitle": "Hướng dẫn apply mobile store-safe. Tín hiệu protected-network phải chặn prompt rủi ro.",
    "policy.metric.apply": "Apply",
    "policy.metric.flush": "Flush",
    "policy.metric.storeSafe": "Store safe",
    "policy.input.title": "Input recommendation",
    "policy.input.subtitle": "Mô phỏng benchmark result hoàn tất đưa vào apply-plan.",
    "policy.testedResolver": "Resolver đã test",
    "policy.protected.title": "Tín hiệu protected network",
    "policy.protected.subtitle": "Các flag này phải ép protect-current-dns hoặc gỡ apply prompt khi cần.",
    "policy.loadPayloads": "Tải policy payload",
    "policy.guided.title": "Guided flow",
    "policy.guided.subtitle": "Flow theo capability OS. App không âm thầm mutate DNS hệ thống.",
    "policy.metric.mutatesDns": "Mutate DNS",
    "policy.metric.steps": "Step",
    "policy.guided.empty": "Tải policy payload để tạo OS guidance flow.",
    "policy.payloads.title": "Payload",
    "policy.payloads.subtitle": "Raw core/CLI JSON có thể select để báo lỗi.",
    "policy.payloads.empty": "Chưa tải policy payload.",
    "policy.option.healthy": "Healthy",
    "policy.option.degraded": "Degraded",
    "policy.option.failed": "Failed",
    "policy.option.inconclusive": "Inconclusive",
    "policy.option.high": "High",
    "policy.option.medium": "Medium",
    "policy.option.low": "Low",

    "storage.title": "Lưu trữ",
    "storage.subtitle": "Custom DNS profile, domain suite, và benchmark history lưu bằng SQLite.",
    "storage.metric.customProfiles": "Custom profile",
    "storage.metric.customSuites": "Custom suite",
    "storage.refresh": "Làm mới storage",
    "storage.profile.title": "Custom DNS Profile",
    "storage.profile.subtitle": "Plain profile có thể benchmark. DoH/DoT profile được lưu cho catalog/apply guidance.",
    "storage.profile.id": "ID",
    "storage.profile.name": "Tên",
    "storage.protocol.plain": "Plain",
    "storage.protocol.doh": "DoH",
    "storage.protocol.dot": "DoT",
    "storage.filtering.none": "Không lọc",
    "storage.filtering.malware": "Malware",
    "storage.filtering.family": "Gia đình",
    "storage.filtering.ads": "Quảng cáo",
    "storage.filtering.security": "Bảo mật",
    "storage.profile.ipv4": "IPv4 server",
    "storage.profile.ipv6": "IPv6 server",
    "storage.profile.doh": "DoH URL",
    "storage.profile.dot": "DoT hostname",
    "storage.profile.tags": "Tag",
    "storage.profile.update": "Cập nhật",
    "storage.suite.title": "Custom Domain Suite",
    "storage.suite.subtitle": "Suite dùng được trong benchmark, compare, path-estimate, và path-compare.",
    "storage.suite.id": "ID",
    "storage.suite.name": "Tên",
    "storage.suite.domains": "Domain",
    "storage.suite.tags": "Tag",
    "storage.suite.add": "Thêm suite",
    "storage.suite.update": "Cập nhật suite",
    "storage.suite.delete": "Xóa suite",
    "storage.history.title": "Lịch sử",
    "storage.history.subtitle": "Được benchmark command lưu khi bật Save history.",
    "storage.history.clear": "Xóa lịch sử",
    "storage.history.empty": "Chưa có benchmark history.",
    "storage.history.record": "{scope} | {mode} | đề xuất {recommendation}",
    "storage.history.delete": "Xóa record",
    "storage.lastResult.title": "CLI result cuối",
    "storage.lastResult.empty": "Chưa có kết quả storage action.",
  },
};

const knownErrors = {
  "Select at least one DNS profile.": {
    vi: "Chọn ít nhất một DNS profile.",
  },
  "Add at least one domain or select a suite.": {
    vi: "Thêm ít nhất một domain hoặc chọn một suite.",
  },
  "Attempts must be a positive whole number.": {
    vi: "Số lần thử phải là số nguyên dương.",
  },
  "DNS timeout must be a positive whole number.": {
    vi: "DNS timeout phải là số nguyên dương.",
  },
  "TCP timeout must be a positive whole number.": {
    vi: "TCP timeout phải là số nguyên dương.",
  },
  "Max targets per domain must be a positive whole number.": {
    vi: "Max target mỗi domain phải là số nguyên dương.",
  },
  "Profile ID or name is required.": {
    vi: "Cần nhập ID hoặc tên profile.",
  },
  "Profile name is required.": {
    vi: "Cần nhập tên profile.",
  },
  "Plain DNS profile needs at least one DNS server.": {
    vi: "Plain DNS profile cần ít nhất một DNS server.",
  },
  "DoH profile needs an https:// URL.": {
    vi: "DoH profile cần URL https://.",
  },
  "DoT profile needs a hostname.": {
    vi: "DoT profile cần hostname.",
  },
  "Suite ID or name is required.": {
    vi: "Cần nhập ID hoặc tên suite.",
  },
  "Suite name is required.": {
    vi: "Cần nhập tên suite.",
  },
  "Suite needs at least one domain.": {
    vi: "Suite cần ít nhất một domain.",
  },
};

export function resolveLocale({ preference = "system", deviceLocales = [] } = {}) {
  const preferred = normalizeLocale(preference);
  if (preference !== "system" && preferred) {
    return preferred;
  }

  for (const locale of Array.isArray(deviceLocales) ? deviceLocales : []) {
    const resolved = normalizeLocale(locale?.languageCode) ?? normalizeLocale(locale?.languageTag);
    if (resolved) {
      return resolved;
    }
  }

  return defaultLocale;
}

export function createTranslator(locale) {
  const resolved = normalizeLocale(locale) ?? defaultLocale;
  return (key, params = {}) => translate(resolved, key, params);
}

export function translate(locale, key, params = {}) {
  const resolved = normalizeLocale(locale) ?? defaultLocale;
  const template = messages[resolved]?.[key] ?? messages[defaultLocale][key] ?? key;
  return interpolate(template, params);
}

export function translateKnownError(locale, message) {
  const resolved = normalizeLocale(locale) ?? defaultLocale;
  return knownErrors[message]?.[resolved] ?? message;
}

function normalizeLocale(value) {
  if (!value || typeof value !== "string") {
    return undefined;
  }
  const language = value.trim().toLowerCase().split(/[-_]/)[0];
  return supportedLocales.includes(language) ? language : undefined;
}

function interpolate(template, params) {
  return String(template).replace(/\{([a-zA-Z0-9_]+)\}/g, (match, name) => {
    const value = params?.[name];
    return value === undefined || value === null ? match : String(value);
  });
}
